apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: ecolator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image }}:{{ .Values.postgres.tag }}"
          ports:
            - containerPort: {{ .Values.postgres.port }}
          envFrom:
            - secretRef:
                name: {{ .Values.postgres.secretName }}
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: {{ .Values.postgres.resources.requests.cpu }}
              memory: {{ .Values.postgres.resources.requests.memory }}
            limits:
              cpu: {{ .Values.postgres.resources.limits.cpu }}
              memory: {{ .Values.postgres.resources.limits.memory }}
          livenessProbe:
            exec:
              command: {{ .Values.postgres.livenessProbe.exec.command | toJson }}
            initialDelaySeconds: {{ .Values.postgres.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.postgres.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.postgres.livenessProbe.failureThreshold }}
          readinessProbe:
            exec:
              command: {{ .Values.postgres.readinessProbe.exec.command | toJson }}
            initialDelaySeconds: {{ .Values.postgres.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.postgres.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.postgres.readinessProbe.failureThreshold }}
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc