apiVersion: v1
kind: Service
metadata:
  name: ai-api
  namespace: ecolator
spec:
  type: ClusterIP
  selector:
    app: ai-api
  ports:
    - name: ai-api
      port: {{ .Values.aiApi.port }}
      targetPort: {{ .Values.aiApi.port }}