apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam
  namespace: ecolator
spec:
  replicas: {{ .Values.iam.replicas }}
  selector:
    matchLabels:
      app: iam
  template:
    metadata:
      labels:
        app: iam
    spec:
      containers:
        - name: iam
          image: "{{ .Values.dockerHubUsername }}/{{ .Values.iam.image }}:{{ .Values.iam.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.iam.port }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/ecolator
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ecolator-db-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecolator-db-secret
                  key: POSTGRES_PASSWORD