apiVersion: v1
kind: Service
metadata:
  name: eco-impact
  namespace: ecolator
spec:
  type: ClusterIP
  selector:
    app: eco-impact
  ports:
    - name: calc
      port: {{ .Values.ecoImpact.port }}
      targetPort: {{ .Values.ecoImpact.port }}