apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecolator-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecolator
  template:
    metadata:
      labels:
        app: ecolator
    spec:
      containers:
        - name: iam
          image: viktorsirakov08/iam-service:v1.0.0
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: postgres-secret
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

        - name: ai-api
          image: viktorsirakov08/ai-api:v1.0.0
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

        - name: eco-impact
          image: viktorsirakov08/eco-impact:v1.0.0
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"