apiVersion: v2
name: ecolator
description: Umbrella chart for All Ecolator Microservices
type: application
version: 0.1.0

dependencies:
  - name: ecoImpact
    version: 0.1.0
    repository: "file://charts/ecoImpact"

  - name: aiApi
    version: 0.1.0
    repository: "file://charts/aiApi"