apiVersion: v2
name: ecolator
description: Umbrella chart for All Ecolator Microservices
type: application
version: 0.1.0

dependencies:
  - name: postgres
    version: 0.1.0
    repository: "file://charts/postgres"

  - name: iam
    version: 0.1.0
    repository: "file://charts/iam"