dockerHubUsername: viktorsirakov08
ecoImpact:
  image: eco-impact
  tag: v1.0.13
  replicas: 2
  port: 8080
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
aiApi:
  image: ai-api
  tag: v1.0.9
  replicas: 2
  port: 8081
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
