apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-api
  namespace: ecolator
spec:
  replicas: {{ .Values.aiApi.replicas }}
  selector:
    matchLabels:
      app: ai-api
  template:
    metadata:
      labels:
        app: ai-api
    spec:
      containers:
        - name: ai-api
          image: "{{ .Values.dockerHubUsername }}/{{ .Values.aiApi.image }}:{{ .Values.aiApi.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.aiApi.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
          resources:
            requests:
              cpu: {{ .Values.aiApi.resources.requests.cpu }}
              memory: {{ .Values.aiApi.resources.requests.memory }}
            limits:
              cpu: {{ .Values.aiApi.resources.limits.cpu }}
              memory: {{ .Values.aiApi.resources.limits.memory }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.aiApi.port }}
            initialDelaySeconds: {{ .Values.aiApi.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.aiApi.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.aiApi.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.aiApi.port }}
            initialDelaySeconds: {{ .Values.aiApi.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.aiApi.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.aiApi.readinessProbe.failureThreshold }}