name: Deploy to Kubernetes

on:
  push:
    branches:
      - docker-k8s
    paths:
      - 'ecolator-chart/values.yaml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Checkout docker-k8s branch
        uses: actions/checkout@v4
        with:
          ref: docker-k8s

      - name: Helm upgrade (Windows)
        if: runner.os == 'Windows'
        run: >
          C:\Windows\System32\helm.exe upgrade --install ecolator ./ecolator-chart
          -n ecolator --create-namespace
          -f ./ecolator-chart/values.yaml
        shell: cmd

      - name: Helm upgrade (Mac/Linux)
        if: runner.os != 'Windows'
        run: >
          helm upgrade --install ecolator ./ecolator-chart
          -n ecolator --create-namespace
          -f ./ecolator-chart/values.yaml