name: Build & Push Eco-Impact Image

on:
  push:
    branches:
      - emissions-calculator
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout service repo
        uses: actions/checkout@v4

      - name: Set version
        id: version
        run: |
          VERSION=v1.0.${GITHUB_RUN_NUMBER}
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./ecolator
          file: ./ecolator/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/eco-impact:${{ steps.version.outputs.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/eco-impact:latest
          
      - name: Checkout docker-k8s branch
        uses: actions/checkout@v4
        with:
          ref: docker-k8s
          path: docker-k8s
          token: ${{ secrets.GH_PAT }}

      - name: Install yq
        run: |
          sudo apt-get update
          sudo apt-get install -y golang-go

          go install github.com/mikefarah/yq/v4@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

          yq --version

      - name: Update Eco Impact Helm values
        run: |
          cd docker-k8s/ecolator-chart
          yq -i '.ecoImpact.tag = "v1.0." + env(GITHUB_RUN_NUMBER)' values.yaml

      - name: Commit and push Helm update
        run: |
          cd docker-k8s

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add ecolator-chart/values.yaml
          git commit -m "eco-impact → v1.0.${GITHUB_RUN_NUMBER}" || echo "No changes"
          git push