dockerHubUsername: viktorsirakov08

ecoImpact:
  image:
    repository: eco-impact
    tag: v1.0.5
  replicas: 2
  port: 8082
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi